---
- name: Setting up Kodo Cloud Server FQDN
  set_fact:
    server_fqdn: "{{ ansible_nodename }}"
  when: server_fqdn is undefined

- name: Using the following Kodo Cloud Server FQDN
  debug:
    msg: "Kodo Cloud Server FQDN: {{ server_fqdn }}"

- name: Add MariaDB repository
  yum_repository:
    name: MariaDB
    description: MariaDB repository
    baseurl: "{{ mariadb_repo_url }}"
    gpgkey: "{{ mariadb_repo_gpg_key }}"
    gpgcheck: yes

- name: Ensure MariaDB repository on CentOS/RHEL 8 has 'module_hotfixes' option enabled
  ini_file:
    path: /etc/yum.repos.d/MariaDB.repo
    section: MariaDB
    option: module_hotfixes
    value: "1"
  when: ansible_distribution_major_version|int >= 8

- name: Add Kodo Cloud repository
  yum_repository:
    name: kodo-cloud
    description: Kodo Cloud repo
    baseurl: "{{ kodo_repo }}"
    gpgcheck: no

- name: Install Kodo Cloud Server and Python-MySQL integration
  yum:
    name:
      - kodo-cloud-server
      - python3-PyMySQL
    state: present

- name: Start and enable MariaDB service
  service:
    name: mariadb
    daemon-reload: yes
    state: started
    enabled: yes

- name: Secure database
  import_tasks: secure_mariadb.yaml

- name: List existing databases
  mysql_info:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    filter:
      - databases
  register: db_list

- name: Initialize Kodo Cloud Server
  shell: "{{ kodo_init_script_path }} --dbrootpassword {{ mariadb_root_password }}"
  when: "kodo_db_name not in db_list.databases"

- name: Start and enable Kodo Cloud Server service
  service:
    name: kodo-cloud-server
    daemon-reload: yes
    state: started
    enabled: yes

- name: Start and enable firewalld service
  service:
    name: firewalld
    daemon-reload: yes
    state: started
    enabled: yes

- name: Firewall - open port 8181
  firewalld:
    port: 8181/tcp
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Firewall - redirect port 443 to 8181
  firewalld:
    rich_rule: "rule family=ipv4 forward-port port=443 protocol=tcp to-port=8181"
    zone: public
    permanent: yes
    immediate: yes
    state: enabled